sudo: false
language: ruby
rvm:
  - 2.2.3
cache:
  - bundler
script:
  - bundle exec rake verify
  - bundle exec rake test
env:
  global:
    # Speeds up installation of nokogiri
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
